### ISSUE TITLE
Windows syntax error

### ISSUE THREAD

**Issue by jwin3** [jamescalixto/global-entry-scraper#1]
I really appreciated you developing this. I was getting a syntax error running this in Windows at line 66. I think it was the -d and -I causing the issue. Removing the dashes fixed the problem for me in Windows. 

I want to run this on a schedule every five minutes. Is there a way of updating the code to not send a discord message if it came back with no time slots? I keep getting a message of no time slots available when I want no message at all.

**Comment by jamescalixto** [comment]
Good catch — [looks like](https://stackoverflow.com/questions/904928/python-strftime-date-without-leading-0) using dashes in `strftime` doesn't work on Windows. I've changed this to less elegant but more functional `replace`.

I've also added the `--silent` flag — when run with this flag, it should suppress messages if there are no open timeslots.
