### ISSUE TITLE
Got notification that slot is available but don't find on TTP website

### ISSUE THREAD

**Issue by pancodia** [jamescalixto/global-entry-scraper#2]
Hi Thank you so much for sharing your work. This is super helpful!

However, when I set up the notification for scanning Nexus appointments. I got notification that a slot is available, however, when I go to the TTP website to book the appointment, I cannot find it. 

Did it happen to you for GE appointment?

Also wonder if there is a automated way to book the slot after found one that is available?

**Comment by jamescalixto** [comment]
If you're in a particularly busy area, it's possible that other people also using this script (or other similar services like [this one](https://appointmentscanner.com/)) are snagging these appointments before you. This did seem to happen to me.

I'm sure there's a way to automatically book a timeslot using [Selenium](https://www.selenium.dev/documentation/webdriver/getting_started/) or similar but that would be a lot more work, and not much faster than trying to book it manually.
